### ISSUE TITLE
Multipart uploads

### ISSUE THREAD

**Issue by smolchanovsky** [nclient/NClient#260]
I would like to be able to send multiple files in a single request or a file with additional information.
See: https://brokul.dev/sending-files-and-additional-data-using-httpclient-in-net-core

**Comment by Kingmidas74** [comment]
Some description is required. Can you provide more info? (Others issues also)

**Comment by smolchanovsky** [comment]
I have added a small description with a link to an example, but I suppose it should be done after these issues:
- https://github.com/nclient/NClient/issues/354
- https://github.com/nclient/NClient/issues/355

**Comment by Kingmidas74** [comment]
We must implement this before 0.12 for dotnet tool generation correct

**Comment by smolchanovsky** [comment]
Necessary features: 
- Support x-www-form-urlencoded
- Support multipart/form-data
- Support FromForm attribute
- Support different serialization types for each part
