### ISSUE TITLE
Add custom attributes support

### ISSUE THREAD

**Issue by Kingmidas74** [nclient/NClient#285]
Custom attributes are helpful for claims checking. However when I describe attributes into implementation of client interface - it's doesn't work. I've tried to use attributes right into interface... Same. Without NClient (default controllers web api) everything works like a charm.
I want to have an opportunity use custom attributes in the class, not in the interface.

**Comment by smolchanovsky** [comment]
@Kingmidas74, thanks for contacting us. We're moving this issue to the 0.9.0 milestone for future evaluation. By the way, don't forget to move your attributes to infra! 😀
