### ISSUE TITLE
MessagePack serialization provider

### ISSUE THREAD

**Issue by smolchanovsky** [nclient/NClient#298]

**Comment by Kingmidas74** [comment]
Hello. 
Are you sure about MessagePack? What do you think about Protobuf? 

I saw the source. Am I correct in understanding that we can write any provider for custom serialization? 
For ex: I need strange formatted like ini. It's possible?

**Comment by smolchanovsky** [comment]
Hi! :) 
I want to implement the most popular serialization formats and provide them via NuGet packages. However, you got it right, if you need exotic serialization, you can implement it yourself and then use it in the client
