### ISSUE TITLE
Inherit interface attributes

### ISSUE THREAD

**Issue by Kingmidas74** [nclient/NClient#397]
What happened in case of one interface inherits from another which contains any attributes like path, etc.

**Comment by smolchanovsky** [comment]
The short answer is yes, attributes will be inherited.
It is worth noting that the inheritance of attributes belonging to an interface and attributes belonging to methods are different: interfaces inherit attributes by default, and methods inherit only if you add an additional attribute - [OverrideAttribute](https://github.com/nclient/NClient/wiki/Annotation#override).
Perhaps this is not obvious behavior...
