### ISSUE TITLE
Think about custom generate serializator 

### ISSUE THREAD

**Issue by Kingmidas74** [nclient/NClient#407]
According to [this list of advice](https://habr.com/ru/company/otus/blog/646793/) (see No. 5), using your custom serializators it better than generic stuff.
Also, System.Text.Json can generate serializators based on DTO. [See this](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/). 

What if we can implements compile-time generation of serializers based on generic T parameter in default provider?

Maybe it could improve performance of NClient.

**Comment by smolchanovsky** [comment]
It seems to be enough to add context to the serializer options, and then pass them to the client:
```C#
var options = new JsonSerializerOptions();
options.AddContext<MyJsonSerializerContext>();

services.AddNClient<IFileClient>(host: "http://localhost:5001", builder =>
    builder.WithSystemTextJsonSerialization(options).Build());
```
By the way, after closing https://github.com/nclient/NClient/issues/410 issue, it will become even easier to do this.

**Comment by smolchanovsky** [comment]
@Kingmidas74, I suggest you write tests to make sure it works :)
