### ISSUE TITLE
Adding HostProvider

### ISSUE THREAD

**Issue by smolchanovsky** [nclient/NClient#448]
The `HostProvider` will allow getting hosts in runtime. Most likely, the provider should be passed to `For` method.

**Comment by Kingmidas74** [comment]
How you suggest use IHostProvider with DI? We should setup host on service.AddNClient(.....)

**Comment by smolchanovsky** [comment]
I think it can look like this:
```C#
serviceCollection.AddRestNClient(implementationFactory: (serviceProvider, builder) =>
{
    var hostProvider = serviceProvider.GetRequiredService<MyHostProvider>();
    builder.For<IMyClient>(hostProvider).Build();
});
```

**Comment by Kingmidas74** [comment]
Well... Maybe we already have this feature?
https://github.com/nclient/NClient/blob/main/tests/NClient.Extensions/NClient.Extensions.DependencyInjection.Tests/AddRestNClientExtensionsTest.cs#L73

**Comment by smolchanovsky** [comment]
Not quite. We can do for example like this:
```C#
serviceCollection.AddRestNClient(implementationFactory: (serviceProvider, builder) => 
{
    var hostProvider = serviceProvider.GetRequiredService<MyHostProvider>();
    var host = hostProvider.Get();
    builder
        .For<IBasicClientWithMetadata>(host)
        .Build()
});
```
This is similar to what I want, but the host provider will create the host only once, since the client is a singleton. Perhaps if we implement https://github.com/nclient/NClient/issues/449#issuecomment-1236070393, it will cover most of the needs. However, we should remember that clients can be created not only using DI.
