### ISSUE TITLE
Selecting the scope for the client in DI

### ISSUE THREAD

**Issue by smolchanovsky** [nclient/NClient#449]
Now clients are created as singletons. This does not allow using non-singleton instance classes to create it.

**Comment by Kingmidas74** [comment]
Do you want additional method like AddRestNClientTransient, AddRestNClientSingleton, etc.. or additional option for current methods?

**Comment by smolchanovsky** [comment]
Ideally, we need both, but perhaps there are enough `AddRestNClientTransient`, `AddRestNClientSingleton` and `AddRestNClientScoped` methods for the first time.

**Comment by Kingmidas74** [comment]
Well... I've done both.
