### ISSUE TITLE
Typo found in README.md

### ISSUE THREAD

**Issue by kolatcole** [nclient/NClient#469]
**Describe the bug**

**To Reproduce**
1. Do this '...'
2. Do that '....'

**Expected behavior**

**Project info (please complete the following information):**
 - Version NClient [e.g. 0.1.0]
 - Version .Net [e.g. .Net 5.0.103]

**Additional context**

**Comment by smolchanovsky** [comment]
I guess that problem was solved in https://github.com/nclient/NClient/pull/470 PR
